### PR TITLE
Packagesh script

### PR DESCRIPTION
**Pull request by pacostas**
This pr
* aligns tools.sh script with the one from node-engine (copy/pasting)
* adds the package.sh file that generates the buildpack.tgz and buildpackage.cnb
* commits the ./bin/pack binary which is the built binary from this pr https://github.com/buildpacks/pack/pull/1661

### CODE REVIEW

**Comment by mhdawson** [comment]
@pacostas I don't think the `.bin` directory should be checked in, other than that it looks good.

**Comment by mhdawson** [comment]
I see your comment about waiting for https://github.com/buildpacks/pack/pull/1661 to land to remove the .bin, but I think it's probably better to just not commit .bin and instead provide instructions somewhere on how to build the versions of pack, jam that you need to use.

**Comment by pacostas** [comment]
I mostly put it there because the github actions are going to need it, the other thing i can do is to add a scripts that downloads this specific version, that way it can also be included in the instructions and also be used by the github actions

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
